Fix link for automated installer
docker/compose-switch pull request #5
Opened 2021-09-29 07:32 UTC by chripede

The link to the automated installer was for compose-cli, not compose-switch

2021-10-04 16:49 UTC, ulyssessouza requested changes

2021-10-04 16:49 UTC, ulyssessouza commented on README.md
> +$ curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sh
LGTM but we could also add the missing `sudo` as you've stated in https://github.com/docker/compose-switch/issues/6

```suggestion
$ curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sudo bash -
```

2021-10-14 21:48 UTC, francislavoie commented
@ndeloof Can we get eyes on this? This mistake caused me to waste quite a lot of time :disappointed:

2021-11-04 21:50 UTC, francislavoie commented
@ndeloof has a decision been made about this? I see compose v2.1.0 was released, but the instructions on https://docs.docker.com/compose/cli-command/ are still outdated, and this repo hasn't been touched in 2 months.

It's still not clear how to actually correctly install docker-compose on linux machines with proper compatibility with old scripts retained.

2021-11-05 08:16 UTC, ndeloof commented
@francislavoie I left Docker, so I can't tell about decision on linux packaging
cc @ulyssessouza @thaJeztah

2022-10-11 19:49 UTC, closed without merging